name: CUDA Medium CI
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read  # to fetch code
  actions: write  # to cancel previous workflows
jobs:
  build:
    name: "build ${{ matrix.name-prefix }} py ${{ matrix.python-version }} CUDA"
    runs-on: "linux-gpu-medium"
    container:
        image: ${{ matrix.container }}
    timeout-minutes: 60
    strategy:
      matrix:
        # Test the oldest and newest supported Python versions here.
        include:
          - name-prefix: "with 3.12"
            python-version: "3.12"
            os: linux-x86
            container: nvidia/cuda:12.3.1-devel-ubuntu20.04
    steps:
    - name: Cancel previous
      uses: styfle/cancel-workflow-action@0.12.0
      with:
        access_token: ${{ github.token }}
      if: ${{github.ref != 'refs/heads/main'}}
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v4
    - name: Run tests
      run: |
        uname -a
        nvidia-smi
